name: Deploy MFW-App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.PEM_PRIVATE_KEY }}" > mfw-key.pem
          chmod 400 mfw-key.pem

      - name: Upload .env to EC2
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
          scp -o StrictHostKeyChecking=no -i mfw-key.pem .env ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/MFW-App/.env

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i mfw-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd MFW-App
            git pull origin main
            sudo docker compose down
            sudo docker compose up -d --build
          EOF
