name: Test SSH to EC2

on:
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PEM_PRIVATE_KEY }}" > ~/.ssh/mfw-key.pem
          chmod 600 ~/.ssh/mfw-key.pem

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/mfw-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo '✅ Hello from GitHub Actions on EC2'"
